In [1]:
import numpy as np

# Creating NumPy array from Python list

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# NumPy methods to generate arrays

In [4]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# To generate linearly spaces numbers between given two numbers 
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
# To create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Generating Random Numbers

In [12]:
# Returns the numbers from a uniform distribution of [0-1]
np.random.rand(2)

array([0.3026284 , 0.99025306])

In [13]:
np.random.rand(2,2)

array([[0.38473736, 0.55900756],
       [0.20091928, 0.88685558]])

In [14]:
# Returns the numbers from a normal distribution with a mean of 0 and a SD of 1
np.random.randn(2)

array([ 0.03941244, -0.50494278])

In [15]:
np.random.randn(2,2)

array([[ 1.30948331,  0.14518679],
       [-1.27344378, -1.98309122]])

In [16]:
np.random.randint(1,10)

4

In [17]:
np.random.randint(1,10,5)

array([9, 8, 5, 4, 8])

# Array attributes and methods

In [18]:
arr = np.arange(1,26)
ranarr = np.random.randint(0,50,10)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
ranarr

array([32, 26, 34, 12, 18, 34, 19, 11, 25, 15])

In [21]:
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr.shape

(5, 5)

In [23]:
ranarr.max()

34

In [24]:
ranarr.argmax()

2

In [25]:
ranarr.min()

11

In [26]:
ranarr.argmin()

7

# Bracket Indexing and Selection

In [27]:
arr = np.arange(0,11)

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

In [31]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
# Array slicing is just a view of the original array. Any changes made to the slice would actually reflect in the actual array
arr = np.arange(0,11)
slice_of_array = arr[0:5]
slice_of_array[:] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [33]:
# Use the copy method to actually copy the content of one array to the another
arr_copy = arr.copy()

# Selection

In [34]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])